#!/bin/bash
# PreToolUse: blocks Edit/Write on the lockfile and generated output.
# Generated dirs/files per .gitignore: dist/, build/, coverage/,
# *.tsbuildinfo, frontend's dev-dist/, playwright-report/, test-results/.
# pnpm-lock.yaml is machine-written by `pnpm install` — hand edits desync it.

if ! command -v jq >/dev/null 2>&1; then
  cat >/dev/null
  echo "guard.sh: jq fehlt – Lockfile-/Generated-Guard kann nicht geprüft werden, Aktion wird blockiert. jq installieren." >&2
  exit 2
fi

INPUT=$(cat)
FILE_PATH=$(jq -r '.tool_input.file_path // empty' <<<"$INPUT")

[ -z "$FILE_PATH" ] && exit 0

deny() {
  echo "$1" >&2
  exit 2
}

case "$FILE_PATH" in
  */pnpm-lock.yaml | pnpm-lock.yaml)
    deny "pnpm-lock.yaml is generated by 'pnpm install' — edit package.json and run install instead."
    ;;
  */dist/* | */build/* | */coverage/* | *.tsbuildinfo | */dev-dist/* | */playwright-report/* | */test-results/*)
    deny "Generated file/output directory — edit the source it's built from instead."
    ;;
esac

exit 0
